title: eeegor
author: Egor Kirpichev
email: egor.kirpichev@gmail.com
avatar: 2017_egor_profile.jpg
location: Berlin, Germany
description: > # this means to ignore newlines until "twitter_username:"
  Hi, I'm Egor. I build things with my <s>hands</s> computer.

show_excerpts: false # set to true to show excerpts on the homepage

# Readymate date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
  # - about.md
  # - writing.md
  # - work.md

# social media profiles
social:
  - channel: Github 
    icon: github.svg
    link: https://github.com/eeegor
  - channel: LinkedIn
    icon: linkedin.svg
    link: https://linkedin.com/in/egor-kirpichev-604395b3
  - channel: Instagram
    icon: instagram.svg
    link: https://instagram.com/egorkirpichev

rss: rss
imprint: imprint.md
google_analytics: UA-64042327-6

# Build settings
# theme: eeegor-jekyll-theme

plugins:
 - jekyll-feed
 - jekyll-seo-tag
